import React from 'react'
import Head from 'next/head'
import {BiUserPlus,BiLogOut} from 'react-icons/bi'
import Table from '/components/table'
import Form from '/components/form'
import {useSelector,useDispatch} from 'react-redux'
import {toggleChangeAction} from '../redux/reducer'
import ConfirmDelete from '/components/confirmDelete'
import { useSession,signOut } from 'next-auth/react'
export default function Home() {
  const visible= useSelector((state)=>{return state.app.visible.toggleForm})
  const  dispatch=useDispatch()
   const session=useSession()
  const handler=()=>{
    dispatch(toggleChangeAction(visible))
  }
  return (
    <section>
      <Head>
        <title>Crud Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' py-2' >
        
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
      Hello world!
    </h1>
     <div className='flex w-full justify-between px-4'>
     {session?session.data?.user?.email:null}
      {session?
      <button 
      className='flex justify-center items-center w-1/6 text-lg   h-9 border rounded-md bg-indigo-400 hover:text-indigo-400 hover:bg-white hover: border-indigo-400'
      onClick={signOut}>
        LogOut <span className='px-2'><BiLogOut size={25} /> </span>
        </button>:null}
      </div>
    <div className='container mx-auto flex justify-between py-5 border-b' >
    <div className='left flex gap-3'>
      <button  onClick={handler} className='flex bg-indigo-400 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-400 hover:text-indigo-400'>
        Add Employee <span className='px-1' ><BiUserPlus size={25} /></span> 
        </button>
    </div>
     {<ConfirmDelete/>}
    </div>
    
   { visible? <Form />:<></>}

    <div className='container mx-auto'>
    <Table />
    </div>
        
      </main>
    </section>
  )
}
